name: homco
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  dropdown_search: ^5.0.6
  searchfield: ^0.7.5
  excel: ^2.0.0-null-safety-3

flutter:
  uses-material-design: true

  assets:
    - assets/complete file.xlsm
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
    - family: Poppins
      fonts: 
        - asset: assets/fonts/Poppins-Regular.ttf
